#ifndef constant
#define constant
#define INPUT_BUFFER_SIZE  200
#define MAX_ARGLIST_SIZE 100
#define PROCESS_STAT_FILE_PATH_STRING_SIZE 50
#define PROCESS_ID_STRING_SIZE 20
#define MAX_NO_OF_COMMANDS 100
#define CPU_UTILIZATION_SAMPLE_INTERVAL 1
#endif